"""
System-wide constants for index and sector symbol names.
"""

# Core Index Symbols
SYMBOL_NIFTY_50 = "NIFTY"
SYMBOL_INDIA_VIX = "INDIA_VIX"

# Sector Indices
SYMBOL_NIFTY_BANK = "NIFTY_BANK"
SYMBOL_NIFTY_IT = "NIFTY_IT"
SYMBOL_NIFTY_AUTO = "NIFTY_AUTO"
SYMBOL_NIFTY_PHARMA = "NIFTY_PHARMA"
SYMBOL_NIFTY_FMCG = "NIFTY_FMCG"
SYMBOL_NIFTY_METAL = "NIFTY_METAL"
SYMBOL_NIFTY_ENERGY = "NIFTY_ENERGY"
SYMBOL_NIFTY_FIN_SERVICE = "NIFTY_FIN_SERVICE"

# Set of all tracked indices
TRACKED_INDICES = {
    SYMBOL_NIFTY_50,
    SYMBOL_INDIA_VIX,
    SYMBOL_NIFTY_BANK,
    SYMBOL_NIFTY_IT,
    SYMBOL_NIFTY_AUTO,
    SYMBOL_NIFTY_PHARMA,
    SYMBOL_NIFTY_FMCG,
    SYMBOL_NIFTY_METAL,
    SYMBOL_NIFTY_ENERGY,
    SYMBOL_NIFTY_FIN_SERVICE,
}

# Lookback duration constants
NIFTY_50_DAYS = 180
INDIA_VIX_DAYS = 35
FII_DII_DAYS = 35


